//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucky.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lucky.Home.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak of {PeakPowerW}W at {PeakPowerTimestamp}.
        ///
        ///Daylight time: {SunTime}
        ///
        ///Peak of grid voltage of {PeakVoltageV}V at {PeakVoltageTimestamp}.
        ///	.
        /// </summary>
        internal static string solar_daily_summary {
            get {
                return ResourceManager.GetString("solar_daily_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Power Peak today: {0:0.0} kWh.
        /// </summary>
        internal static string solar_daily_summary_title {
            get {
                return ResourceManager.GetString("solar_daily_summary_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h&apos; hours and &apos;mm&apos; minutes&apos;.
        /// </summary>
        internal static string solar_daylight_format {
            get {
                return ResourceManager.GetString("solar_daylight_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string solar_error_mail_error {
            get {
                return ResourceManager.GetString("solar_error_mail_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , solved after {0} seconds..
        /// </summary>
        internal static string solar_error_mail_error_solved {
            get {
                return ResourceManager.GetString("solar_error_mail_error_solved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string solar_error_mail_normal {
            get {
                return ResourceManager.GetString("solar_error_mail_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverter Errors.
        /// </summary>
        internal static string solar_error_mail_title {
            get {
                return ResourceManager.GetString("solar_error_mail_title", resourceCulture);
            }
        }
    }
}
